[tool.bumpversion]
current_version = "0.1.4"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "docs/source/conf.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "src/af_analysis/__init__.py"

[[tool.bumpversion.files]]
filename = "src/af_analysis/analysis.py"

[[tool.bumpversion.files]]
filename = "src/af_analysis/clustering.py"

[[tool.bumpversion.files]]
filename = "src/af_analysis/data.py"

[[tool.bumpversion.files]]
filename = "src/af_analysis/docking.py"
